### ISSUE TITLE
Error when running monitor on illumination correction

### ISSUE THREAD

**Issue by bethac07** [CellProfiler/Distributed-CellProfiler#98]
AFAICT, currently a one-off, running current master (917922c) :

```
An error occurred (InvalidParameter) when calling the DescribeSpotFleetRequestHistory operation: Parameter StartTime must be a valid time in the past.
Traceback (most recent call last):
 File “run.py”, line 391, in <module>
   monitor()
 File “run.py”, line 308, in monitor
   killdeadAlarms(fleetId,monitorapp)
 File “run.py”, line 43, in killdeadAlarms
   for eachevent in datedead[‘HistoryRecords’]:
TypeError: string indices must be integers, not str
```

**Comment by bethac07** [comment]
Checked the same command on the same spot fleet now, now running fine, need more data to proceed.

**Comment by bethac07** [comment]
This happens at midnight apparently!  Need to put in a "if time ends in 0, but is  not 00:00" evidently

**Comment by shntnu** [comment]
> This happens at midnight apparently! Need to put in a "if time ends in 0, but is not 00:00" evidently

^ I can verify this

```
2020-03-25 00:00:18.600385 In process: 8 Pending 0

An error occurred (InvalidParameter) when calling the DescribeSpotFleetRequestHistory operation: Parameter StartTime must be a valid time in the past.
Traceback (most recent call last):
  File "run.py", line 391, in <module>
    monitor()
  File "run.py", line 308, in monitor
    killdeadAlarms(fleetId,monitorapp)
  File "run.py", line 43, in killdeadAlarms
    for eachevent in datedead['HistoryRecords']:
TypeError: string indices must be integers, not str
ubuntu@ip-10-0-9-250:~/efs/2018_06_05_cmQTL/workspace/software/Distributed-CellProfiler$
ubuntu@ip-10-0-9-250:~/efs/2018_06_05_cmQTL/workspace/software/Distributed-CellProfiler$
ubuntu@ip-10-0-9-250:~/efs/2018_06_05_cmQTL/workspace/software/Distributed-CellProfiler$
ubuntu@ip-10-0-9-250:~/efs/2018_06_05_cmQTL/workspace/software/Distributed-CellProfiler$ python run.py monitor files/2018_06_05_cmQTL_AnalysisSpotFleetRequestId.json
2020-03-25 00:07:59.391687 In process: 4 Pending 0
```

**Comment by shntnu** [comment]
I'm on fa2e17c2936c09776e1f4d5157d8bee14353c9fb but its possible that I may have pulled after starting the process.

**Comment by bethac07** [comment]
Sorry, I had made the change in a branch but had forgotten to pull! If you pull master now you should avoid in the future.
